# Generated by Django 4.2.5 on 2023-10-25 11:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Distinctive name of the school",
                        max_length=100,
                        unique=True,
                        verbose_name="School",
                    ),
                ),
            ],
            options={
                "verbose_name": "School",
                "verbose_name_plural": "Schools",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("principal", "Principal"),
                            ("mobman", "Mobility Manager"),
                        ],
                        help_text="Kind of role that this users assume in this schools",
                        max_length=50,
                        verbose_name="Kind",
                    ),
                ),
                (
                    "max_users",
                    models.SmallIntegerField(
                        blank=True,
                        default=0,
                        help_text="Maximum number of users that can assume this role in this schools (0=unlimited)",
                        verbose_name="Max Users",
                    ),
                ),
                (
                    "schools",
                    models.ManyToManyField(
                        help_text="Schools where this role is assumed by this users",
                        related_name="roles",
                        to="momain.school",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        help_text="Users that can assume this role in this schools",
                        related_name="roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "ordering": ["schools__name", "kind"],
            },
        ),
    ]
