# Generated by Django 4.2.5 on 2023-10-25 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("momain", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="max_users",
        ),
        migrations.AlterField(
            model_name="role",
            name="schools",
            field=models.ManyToManyField(
                blank=True,
                help_text="Schools where this role is assumed by this users",
                related_name="roles",
                to="momain.school",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users that can assume this role in this schools",
                related_name="roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
