# Generated by Django 4.2.5 on 2023-10-25 14:39

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    group_name = 'momain_admin'
    if not Group.objects.filter(name=group_name).exists():
        obj = Group(name=group_name)
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("momain", "0002_remove_role_max_users_alter_role_schools_and_more"),
        ("auth", "0001_initial")
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
