# Generated by Django 4.2.5 on 2023-10-31 14:26

from django.db import migrations, models
import rules.contrib.models


class Migration(migrations.Migration):
    dependencies = [
        ("momain", "0003_auto_20231025_1439"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={"verbose_name": "Role", "verbose_name_plural": "Roles"},
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Distinctive name of the campaign",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "stamp_start",
                    models.DateTimeField(
                        help_text="Instant when the campaign becomes active"
                    ),
                ),
                (
                    "stamp_end",
                    models.DateTimeField(
                        help_text="Instant when the campaign stops to be active"
                    ),
                ),
                (
                    "schools",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Schools this campaign is about",
                        related_name="campaigns",
                        to="momain.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
