# Generated by Django 4.2.5 on 2023-11-16 14:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("momain", "0006_auto_20231116_1420"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="uuid",
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="school",
            name="uuid",
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False),
        ),
    ]
