# Generated by Django 4.2.5 on 2023-11-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("momain", "0009_school_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="Complete address of the school",
                max_length=300,
                null=True,
                verbose_name="Address",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="school",
            name="lng",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
