# Generated by Django 4.2.5 on 2023-11-24 15:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("momain", "0012_alter_link_network_alter_stage_network"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Link",
        ),
    ]
