# Generated by Django 4.2.5 on 2023-11-24 17:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import rules.contrib.models


class Migration(migrations.Migration):
    dependencies = [
        ("momain", "0013_delete_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("netid", models.CharField(max_length=100)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326),
                ),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="momain.network",
                    ),
                ),
            ],
            options={
                "verbose_name": "Link",
                "verbose_name_plural": "Links",
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name="stage",
            name="dest_geom",
        ),
        migrations.RemoveField(
            model_name="stage",
            name="dest_stamp",
        ),
        migrations.RemoveField(
            model_name="stage",
            name="netid",
        ),
        migrations.RemoveField(
            model_name="stage",
            name="network",
        ),
        migrations.RemoveField(
            model_name="stage",
            name="orig_geom",
        ),
        migrations.RemoveField(
            model_name="stage",
            name="orig_stamp",
        ),
        migrations.RemoveField(
            model_name="stage",
            name="trav_dist",
        ),
        migrations.RemoveField(
            model_name="stage",
            name="trav_time",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="modes",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="trav_dist",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="trav_time",
        ),
        migrations.AddField(
            model_name="stage",
            name="info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="extid",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="stage",
            name="mode",
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name="Trait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ord", models.IntegerField(blank=True, default=0)),
                ("submode", models.CharField(blank=True, max_length=10, null=True)),
                ("trav_dist", models.FloatField(blank=True, null=True)),
                ("trav_time", models.FloatField(blank=True, null=True)),
                (
                    "link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="traits",
                        to="momain.link",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traits",
                        to="momain.stage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trait",
                "verbose_name_plural": "Traits",
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
