# Generated by Django 4.2.5 on 2024-01-05 15:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("momain", "0014_link_remove_stage_dest_geom_remove_stage_dest_stamp_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ViewDashheat",
            fields=[
                (
                    "extid",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("campaign_id", models.BigIntegerField()),
                ("school_id", models.BigIntegerField()),
                ("mode", models.CharField(max_length=10)),
                ("flow", models.BigIntegerField(blank=True, null=True)),
                ("min_trav_dist", models.FloatField(blank=True, null=True)),
                ("max_trav_dist", models.FloatField(blank=True, null=True)),
                ("avg_trav_dist", models.FloatField(blank=True, null=True)),
                ("min_trav_time", models.FloatField(blank=True, null=True)),
                ("max_trav_time", models.FloatField(blank=True, null=True)),
                ("avg_trav_time", models.FloatField(blank=True, null=True)),
                (
                    "orig_geom",
                    django.contrib.gis.db.models.fields.GeometryField(srid=4326),
                ),
            ],
            options={
                "db_table": "momain_dashheat",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ViewDashlink",
            fields=[
                (
                    "campaign_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("data", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "momain_dashlink",
                "managed": False,
            },
        ),
    ]
