# Generated by Django 4.2.5 on 2024-01-05 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("momain", "0015_viewdashheat_viewdashlink"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign_schools",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="momain.campaign",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="momain.school"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="campaign",
            name="schools",
            field=models.ManyToManyField(
                blank=True,
                help_text="Schools this campaign is about",
                related_name="campaigns",
                through="momain.Campaign_schools",
                to="momain.school",
            ),
        ),
    ]
