# Generated by Django 4.2.5 on 2024-01-05 15:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("momain", "0016_campaign_schools_alter_campaign_schools"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Campaign_schools",
            new_name="Cascho",
        ),
        migrations.AlterModelTable(
            name="cascho",
            table="momain_campaign_schools",
        ),
    ]
