# Generated by Django 4.2.5 on 2024-01-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("momain", "0017_rename_campaign_schools_cascho_alter_cascho_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="students",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
