# Generated by Django 4.2.5 on 2024-02-02 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("momain", "0019_trip_direction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cascho",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="caschos",
                to="momain.campaign",
            ),
        ),
        migrations.AlterField(
            model_name="cascho",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="caschos",
                to="momain.school",
            ),
        ),
    ]
