# Generated by Django 4.2.5 on 2024-02-08 11:27

from django.db import migrations, models
import momain.models


class Migration(migrations.Migration):
    dependencies = [
        ("momain", "0021_viewdash"),
    ]

    operations = [
        migrations.CreateModel(
            name="ViewDashtrip",
            fields=[
                (
                    "campaign_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("school_id", models.BigIntegerField(blank=True, null=True)),
                ("mode", models.CharField(blank=True, max_length=10, null=True)),
                ("network_id", models.BigIntegerField(blank=True, null=True)),
                ("netid", models.CharField(blank=True, max_length=100, null=True)),
                ("flow", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "momain_dashtrip",
                "managed": False,
            },
            bases=(models.Model, momain.models.ByUserMixin),
        ),
    ]
