# Generated by Django 4.2.5 on 2024-02-09 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("momain", "0022_viewdashtrip"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaign",
            options={
                "ordering": ["-stamp_start", "-stamp_end"],
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
            },
        ),
    ]
