# Generated by Django 4.2.5 on 2024-02-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("momain", "0023_alter_campaign_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="trait",
            name="info",
            field=models.TextField(blank=True, null=True),
        ),
    ]
