# Generated by Django 4.2.5 on 2024-02-23 15:50

from django.db import migrations

def copy_info(apps, schema_editor):
    Stage = apps.get_model("momain", "Stage")
    for stage in Stage.objects.all():
        for trait in stage.traits.all():
            trait.info = stage.info
            trait.save()


class Migration(migrations.Migration):
    dependencies = [
        ("momain", "0024_trait_info"),
    ]

    operations = [
        migrations.RunPython(copy_info),        
    ]
