# Generated by Django 4.2.5 on 2024-02-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("momain", "0026_remove_stage_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="trait",
            name="flow",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trait",
            name="graphid",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
