# Generated by Django 4.2.5 on 2024-02-23 16:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("momain", "0027_trait_flow_trait_graphid"),
    ]

    operations = [
        migrations.AddField(
            model_name="stage",
            name="dest_address",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="stage",
            name="dest_geom",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="stage",
            name="dest_stamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stage",
            name="orig_address",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="stage",
            name="orig_geom",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="stage",
            name="orig_stamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
