# Generated by Django 4.2.5 on 2024-02-23 16:23

from django.db import migrations

def copy_data(apps, schema_editor):
    Stage = apps.get_model("momain", "Stage")
    for stage in Stage.objects.all():
        stage.orig_stamp = stage.trip.orig_stamp
        stage.dest_stamp = stage.trip.dest_stamp
        stage.orig_address = stage.trip.orig_address
        stage.dest_address = stage.trip.dest_address
        stage.orig_geom = stage.trip.orig_geom
        stage.dest_geom = stage.trip.dest_geom
        stage.save()


class Migration(migrations.Migration):
    dependencies = [
        ("momain", "0028_stage_dest_address_stage_dest_geom_stage_dest_stamp_and_more"),
    ]

    operations = [
        migrations.RunPython(copy_data),
    ]
