# Generated by Django 4.2.5 on 2024-02-23 16:23

from django.db import migrations

def set_flow(apps, schema_editor):
    Trait = apps.get_model("momain", "Trait")
    for trait in Trait.objects.all():
        trait.flow = 1.0
        trait.save()


class Migration(migrations.Migration):
    dependencies = [
        ("momain", "0029_auto_20240223_1723"),
    ]

    operations = [
        migrations.RunPython(set_flow),
    ]
