# Generated by Django 4.2.5 on 2024-04-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("momain", "0030_auto_20240223_1727"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
