# Generated by Django 4.2.5 on 2024-04-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("momain", "0031_school_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="survey",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
